name: ce_automation
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - mysql=8.0.23
  - mysql-connector-python=8.0.23
  - pylint=2.7.2
  - schedule=1.0.0
  - googlemaps=2.5.1
  - numpy=1.18.4
  - pandas=1.0.3
  - pyyaml=5.4.1
  - matplotlib==3.2.2
  - scipy=1.6.3
  - seaborn=0.11.1
  - pysolar=0.9
  - windrose==1.6.8
  - timezonefinder=5.2.0
  - geopy=2.1.0
  - geographiclib=1.50
  - pip=21.1.1
  - pip:
    - psychrochart==0.2.6
    - psychrolib==2.5.0
    #- googlemaps==2.5.1
    
